### ISSUE TITLE
[RFC] MaContainer component

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#375]
Hello team,

There is one issue is been bugging me for a while and that is the lack of a "container" layout component. I honestly think it should be in our DS so here's my idea.

## What is a container?

I'm refering to a "container" (in lack of a better name) to something that has a responsive max-width a margin: auto and a padding. For example, this:

![image](https://user-images.githubusercontent.com/4160121/111291865-e9e79380-8647-11eb-87f3-ae63f26e8e42.png)

In this specific example (you can see it [here](https:///alta-staging.holaluz.com) in action), this container has a variable max-width, depending on the width of the screen. It also has a margin auto to always center content in the middle and a padding, so that mobile layouts don't "glue" to the sides of the screen.

## Why variable max-width? Why not a single max-width?

This is a legacy issue that the DS should try to fix IMHO. This is a snippet of what our old DS did:

```css
@include mq($from: sm) {
    max-width: 540px;
}

@include mq($from: md) {
    max-width: 720px;
}

@include mq($from: lg) {
    max-width: 960px;
}

@include mq($from: xl) {
    max-width: 1180px;
}
```
Changing this will break designs in dryMartini and maitai. I'm just saying this so that we have it in mind for this RFC or even for deciding if we need this component in the DS or not.

I also kinda like the idea of having multiple max-widths, even if it means losing "screen real estate" for smaller devices. It's easier to do the responsive if we have the max-widths more controlled.

Of course, if we do "responsive" max widths, they should be done with the responsive props that we have right now in margarita (not with the mess that we had before).

Well, this is something we should discuss together in the DS meetings anyways.

## API example:

The only prop we should have is the `max-width`. Which should depend on what the DS sets as our standard container sizes. If there is the same max-width on all of our apps (which I doubt), remove the prop altogether.
```vue
<ma-container
    size="medium" // the standard container size, for example maitai.
/>
```
```vue
<ma-container
    size="small" // a small container size, for example embeds or email templates
    // (if we could put margarita on emails hahah)
/>
```
```vue
<ma-container
    size="large" // large container sizes, for example dashboards
/>
```
We could also explore the idea of a variable size using the responsive props (passing an array like ma-stack space).

What do you guys think? Would this be useful? Is it too situational and we will only use it in dry/maitai/oneclicksales? 

Let's discuss it! 😃

**Comment by afontcu** [comment]
> Is it too situational and we will only use it in dry/maitai/oneclicksales?

I think we'd use it almost everywhere! Let's do this.

---


I'm not entirely sure about the "dynamic" max-width, because we could do something like:

```vue
<ma-container :size="['small', 'medium', 'large']">...</ma-container>
```

in case of wanting it to change depending on the breakpoint. That being said, we've set some responsive values for MaText/Heading, so I'm OK with this, too 👍  I guess this is for design folks to decide :)

**Comment by cillascillas** [comment]
+1 to the MaContainer proposal!
About the width, I'd rather go for a container that is responsive and behaves in a way depending the breakpoint that for a definition of which container should be in every 'step'. But as you two said, let's ask the design team about it! Maybe they have a way of working when designing and have "default" containers/measures/good practices for breakpoints.

**Comment by carlotamolintr** [comment]
Breakpoints of each repo:
 
 **Kalimotxo:** 
```
 @custom-media --breakpoint-md (min-width: 768px);
@custom-media --breakpoint-lg (min-width: 992px);
```

**Dry-martini:**
- all sass breakpoints (margarita)
```
@mixin forShittyLaptop {
  @media (max-height: 40rem) {
    @content;
  }
}
```
- **Maitai**:
- all sass breakpoints (margarita)

**Comment by alexcastelo95** [comment]
### Bonasera breakpoints

- @custom-media --breakpoint-xs (min-width: 380px);
- @custom-media --breakpoint-sm (min-width: 576px);
- @custom-media --breakpoint-md (min-width: 768px);
- @custom-media --breakpoint-lg (min-width: 992px);
- @custom-media --breakpoint-xl (min-width: 1200px);

- all sass breakpoints (margarita)

**Comment by afontcu** [comment]
Hi folks! we're not looking for all breakpoints of each project, but rather **the "container" classes/components of each project**, so that we know what values we should take into account when designing MaContainer.

**Comment by alexcastelo95** [comment]
## Layouts in Bonasera
I have identified 3 types of possible layouts in `Bonasera`:

### Nuxt layouts
**DEFAULT:**
``` scss
.app {
  display: flex;
  flex-direction: column;
  min-height: 100vh;

  &__content {
    display: flex;
    position: relative;
    flex-direction: column;
    flex-grow: 1;
  }
}
```

**ERROR:**
``` scss
.error {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: auto;
  max-width: 19.68rem;

  &__content {
    margin-top: 1.313rem;
  }
}
```

**FULL-SCREEN:**
``` css
.app__content {
  display: flex;
  flex: 1;
  align-items: center;
  justify-content: center;
}
```

### Scss assets
I don't think it's used anywhere, though.
``` scss
.container {
  position: relative;
  margin-right: auto;
  margin-left: auto;
  width: 100%;

  &--medium {
    max-width: 70rem;
  }

  &--small {
    max-width: 56.25rem;
  }
}
```

And finally, and I think the ones we are most interested in, the ones I have seen used in the components. Of these, there are mainly 2 groups: forms and data representation (tables or cards). I have called them in this way a bit random. 😹 

**Forms:** is the typical form wrapper that is used in all `Bonasera`:
```css
.form-wrapper {
  max-width: 52.5rem !important;
}
```

**DATA TABLES:** In other parts of `Bonasera`, such as contracts, pending contracts, clients, etc. we usually follow the format of a browser and a table, from what I've seen the widths used are similar to this: 
```scss
.contract { 
max-width: 70rem;
****
}
```

There are small modifications with media queries, padding, and grid template areas. Nothing critical.
